library(argparser)
p <- arg_parser("Description")
p <- add_argument(p, "fa", help="genome fa", type="character")
p <- add_argument(p, "gtf", help="gencode gtf", type="character")
p <- add_argument(p, "outdir", help="output directory", type="character")
p <- add_argument(p, "--cores", default = 60, help="parallel cores", type = "integer")
argv <- parse_args(p)

library(scAFAP)
prepare_anno(argv$fa, argv$gtf, argv$outdir, argv$cores)
